version: '3.3'
services:
  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: task
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - '~/.mysql-data/db:/var/lib/mysql'
    networks:
      - nestjs-network

  backend:
    container_name: car_driver
    restart: always
    build: ./
    ports:
      - '3000:3000'
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: task
      DB_USER: user
      DB_PASSWORD: root
      DB_SYNCHRONIZE: 'true'
    depends_on:
      - database
    networks:
      - nestjs-network

networks:
  nestjs-network:
    external: false